CI: Pin actions/upload-artifact to v4.3.5 for windows-patches
Work around a bug with too many open files in versions before v4.3.5 and
also in v4.3.6 due to a revert. The relevant error message is:

Error: EMFILE: too many open files