mac-avcapture: Fix NSString being initialized with NULL
Calling [NSString stringWithUTF8String:] with NULL causes it to raise an
exception: +[NSString stringWithUTF8String:]: NULL cString